TeaTracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls), path("", include("tea.urls"))]

tea/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main-page"),
    path("profil", views.ProfileSelectView.as_view(), name="profile-select"),
    path("profil/dodaj", views.ProfileCreateView.as_view(), name="create-profile"),
    path("herbaty", views.AllTeasView.as_view(), name="all-teas"),
    path("herbaty/dodaj", views.TeaCreateView.as_view(), name="create-tea"),
    path("herbaty/dodaj/sklep", views.StoreCreateView.as_view(), name="create-store"),
    path("herbaty/dodaj/typ", views.TypeCreateView.as_view(), name="create-type"),
    path(
        "herbaty/dodaj/kultywar",
        views.CultivarCreateView.as_view(),
        name="create-cultivar",
    ),
    path(
        "herbaty/dodaj/kraj", views.CountryCreateView.as_view(), name="create-country"
    ),
    path(
        "herbaty/dodaj/prowincja",
        views.ProvinceCreateView.as_view(),
        name="create-province",
    ),
    path(
        "herbaty/dodaj/region", views.RegionCreateView.as_view(), name="create-region"
    ),
    path("herbaty/<slug:slug>", views.TeaDetailView.as_view(), name="tea-detail"),
    path(
        "herbaty/<slug:slug>/edytuj", views.TeaUpdateView.as_view(), name="tea-update"
    ),
    path(
        "herbaty/<slug:slug>/parzenia/",
        views.BrewListView.as_view(),
        name="brews-list",
    ),
    path(
        "herbaty/<slug:slug>/parzenia/dodaj",
        views.BrewCreateView.as_view(),
        name="create-brew",
    ),
    path(
        "herbaty/parzenie/<int:pk>",
        views.BrewDetailView.as_view(),
        name="brew-detail",
    ),
    path(
        "herbaty/parzenie/<int:pk>/edytuj",
        views.BrewUpdateView.as_view(),
        name="brew-update",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tea/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

# Create your models here.


class Profile(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=_("Nazwa"))

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("Profil")
        verbose_name_plural = _("Profile")


class Store(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=_("Nazwa"))
    website = models.URLField(unique=True, verbose_name=_("Strona internetowa"))

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("Sklep")
        verbose_name_plural = _("Sklepy")


class Type(models.Model):
    name = models.CharField(max_length=25, unique=True, verbose_name=_("Nazwa"))

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("Typ herbaty")
        verbose_name_plural = _("Typy herbaty")


class Cultivar(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=_("Nazwa"))

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("Kultywar")
        verbose_name_plural = _("Kultywary")


class Country(models.Model):
    name = models.CharField(max_length=25, unique=True, verbose_name=_("Nazwa"))

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("Kraj")
        verbose_name_plural = _("Kraje")


class Province(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name=_("Nazwa"))
    country = models.ForeignKey(
        Country, on_delete=models.CASCADE, verbose_name=_("Kraj")
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("Prowincja")
        verbose_name_plural = _("Prowincje")


class Region(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name=_("Nazwa"))
    province = models.ForeignKey(
        Province, on_delete=models.CASCADE, verbose_name=_("Prowincja")
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("Region")
        verbose_name_plural = _("Regiony")


class Tea(models.Model):
    SEASON_CHOICES = [("W", "Wiosna"), ("L", "Lato"), ("J", "Jesień"), ("Z", "Zima")]

    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, verbose_name=_("Profil")
    )
    name = models.CharField(max_length=100, verbose_name=_("Nazwa"))
    slug = models.SlugField(unique=True)
    store = models.ForeignKey(
        Store, null=True, blank=True, on_delete=models.SET_NULL, verbose_name=_("Sklep")
    )

    price_per_100_grams = models.FloatField(
        validators=[MinValueValidator(1)], verbose_name=_("Cena za 100 gramów")
    )
    grams_left = models.IntegerField(
        validators=[MinValueValidator(0)], verbose_name=_("Pozostało gramów")
    )
    score = models.IntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(1), MaxValueValidator(10)],
        verbose_name=_("Ocena"),
    )

    date_added = models.DateTimeField(auto_now_add=True)
    last_viewed = models.DateTimeField(default=timezone.now, blank=True)
    date_finished = models.DateField(null=True, blank=True)

    store_description = models.TextField(blank=True, verbose_name=_("Opis sprzedawcy"))
    user_description = models.TextField(blank=True, verbose_name=_("Opis własny"))
    tasting_notes = models.TextField(blank=True, verbose_name=_("Nuty smakowe"))
    additional_notes = models.TextField(blank=True, verbose_name=_("Dodatkowe uwagi"))

    country = models.ForeignKey(
        Country,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_("Kraj"),
    )
    province = models.ForeignKey(
        Province,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_("Prowincja"),
    )
    region = models.ForeignKey(
        Region,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_("Region"),
    )

    type = models.ForeignKey(
        Type,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_("Typ herbaty"),
    )
    cultivar = models.ForeignKey(
        Cultivar,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_("Kultywar"),
    )

    season = models.CharField(
        blank=True, max_length=1, choices=SEASON_CHOICES, verbose_name=_("Sezon")
    )
    year = models.IntegerField(null=True, blank=True, verbose_name=_("Rok"))
    harvest_date = models.DateField(
        null=True, blank=True, verbose_name=_("Data zbiorów")
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("Herbata")
        verbose_name_plural = _("Herbaty")


class Image(models.Model):
    tea = models.ForeignKey(Tea, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="tea-images")

    def __str__(self) -> str:
        return f"{self.id} - {self.tea.name}"

    class Meta:
        verbose_name = _("Zdjęcie")
        verbose_name_plural = _("Zdjęcia")


class Brew(models.Model):
    tea = models.ForeignKey(Tea, on_delete=models.CASCADE)
    brew_date = models.DateField(auto_now_add=True)
    tasting_notes = models.TextField(verbose_name=_("Opis"))
    grams = models.FloatField(
        validators=[MinValueValidator(0.1)],
        null=True,
        blank=True,
        verbose_name=_("Gramy"),
    )
    water_ml = models.IntegerField(
        validators=[MinValueValidator(1)],
        null=True,
        blank=True,
        verbose_name=_("Ilość wody (ml)"),
    )
    ratio = models.FloatField(null=True, blank=True, verbose_name=_("Stosunek"))

    def __str__(self) -> str:
        return f"{self.tea.name} {self.brew_date}"

    class Meta:
        verbose_name = _("Parzenie")
        verbose_name_plural = _("Parzenia")


class BrewImage(models.Model):
    brew = models.ForeignKey(Brew, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="brew-images")

    def __str__(self) -> str:
        return f"{self.id} - {self.brew.brew_date} - {self.brew.tea}"

    class Meta:
        verbose_name = _("Zdjęcie parzenia")
        verbose_name_plural = _("Zdjęcia parzeń")

tea/forms.py
from __future__ import annotations

from datetime import date
from typing import Any, Dict

from django import forms

from . import models


class ProfileSelectForm(forms.ModelForm):
    class Meta:
        model = models.Tea
        fields = ["profile"]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ["name"]


class TeaForm(forms.ModelForm):
    class Meta:
        model = models.Tea
        fields = [
            "name",
            "price_per_100_grams",
            "grams_left",
            "season",
            "year",
            "harvest_date",
            "store",
            "type",
            "cultivar",
            "country",
            "province",
            "region",
            "store_description",
            "user_description",
            "tasting_notes",
            "additional_notes",
        ]
        widgets = {
            "harvest_date": forms.DateInput(
                format="%d-%m-%Y",
                attrs={"type": "date"},
            ),
        }

    def clean(self) -> Dict[str, Any]:
        cleaned_data = super(TeaForm, self).clean()

        harvest_year = (
            cleaned_data.get("year") if cleaned_data.get("year") is not None else 1
        )
        if harvest_year > date.today().year:
            self.add_error("year", "Rok produkcji jest większy niż aktualny rok!")

        harvest_date = (
            cleaned_data.get("harvest_date")
            if cleaned_data.get("harvest_date") is not None
            else date(1, 1, 1)
        )
        if harvest_date > date.today():
            self.add_error("harvest_date", "Data zbiorów jest w przyszłości!")

        if harvest_year != harvest_date.year:
            self.add_error("year", "Rok nie zgadza się z datą zbiorów!")

        return cleaned_data


class StoreForm(forms.ModelForm):
    class Meta:
        model = models.Store
        fields = ["name", "website"]


class TypeForm(forms.ModelForm):
    class Meta:
        model = models.Type
        fields = ["name"]


class CultivarForm(forms.ModelForm):
    class Meta:
        model = models.Cultivar
        fields = ["name"]


class CountryForm(forms.ModelForm):
    class Meta:
        model = models.Country
        fields = ["name"]


class ProvinceForm(forms.ModelForm):
    class Meta:
        model = models.Province
        fields = ["name", "country"]


class RegionForm(forms.ModelForm):
    class Meta:
        model = models.Region
        fields = ["name", "province"]


class BrewForm(forms.ModelForm):
    class Meta:
        model = models.Brew
        fields = ["grams", "water_ml", "tasting_notes"]

tea/templates/tea/all-teas.html
{% extends "base.html" %}
{% load static %}

{% block css_files %}
    <link rel="stylesheet" href="{% static "tea/all-teas.css" %}">
{% endblock %}

{% block title %}Wszystkie herbaty{% endblock title %}

{% block content %}
    <main id="main-content">
        <article id="all-teas">
            {% if teas %}
                <h2>Lista herbat</h2>
                <ul id="all-teas-list">
                    {% for tea in teas %}
                        <li>
                            <a href="{% url "tea-detail" slug=tea.slug %}">
                                {% if tea.image_set.first.image.url %}
                                    <img class="tea-image" src="{{ tea.image_set.first.image.url }}" alt="Zdjęcie herbaty"/>
                                {% else %}
                                    <img class="tea-image" src="{% static "images/default_tea.png" %}" alt="Rysunek liści herbaty, brak zdjęć"/>
                                {% endif %}
                                <h3>{{ tea.name }}</h3>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>Brak herbat w bazie danych!</p>
                <p>Możesz dodać nową herbatę przyciskiem w górnym pasku.</p>
            {% endif %}
        </article>
    </main>
{% endblock  %}

tea/templates/tea/brew-detail.html
{% extends "base.html" %}
{% load static %}

{% block css_files %}
    <link rel="stylesheet" href="{% static "tea/brew-detail.css" %}">
{% endblock %}

{% block title %}Parzenie{{ brew.tea.name }}{% endblock title %}

{% block content %}
    <main id="main-content">
        <h1 id="name">Parzenie {{ brew.tea.name }}</h1>
        <p id="date">{{ brew.brew_date }}</p>
        <div id="above-details">
            <section id="buttons">
                <a href="{% url "brew-update" pk=brew.pk %}" id="update-button" class="button">Edytuj</a>
                <a href="" id="delete-button" class="button">Usuń</a>
            </section>
        </div>
        <section id="brew-details">
            <div class="separator"><b>GRAMY I WODA</b></div>
            <p><b>Ilość herbaty (g):</b> {{ brew.grams }} g</p>
            <p><b>Ilość wody (ml):</b> {{ brew.water_ml }} ml</p>
            <p><b>Stosunek:</b> {{ brew.ratio }} g / 100 ml</p>
        </section>
        <section id="description">
            <div class="separator"><b>OPIS</b></div>
            <p>{{ brew.tasting_notes }}</p>
        </section>
    </main>
{% endblock %}

tea/templates/tea/brews-list.html
{% extends "base.html" %}
{% load static %}

{% block css_files %}
    <link rel="stylesheet" href="{% static "tea/brews-list.css" %}">
{% endblock %}

{% block title %}Parzenia{% endblock title %}

{% block content %}
    <main id="main-content">
        <h2>Parzenia {{ tea_name }}</h2>
        <div id="above-brews">
            <section id="buttons">
                <a href="{% url "create-brew" slug=tea_slug %}" id="create-brew-button" class="button">Dodaj parzenie</a>
            </section>
        </div>
        <article id="all-brews">
            {% if brews %}
                <table id="brews-table">
                    <caption><b>Lista parzeń</b></caption>
                    <tr>
                        <th>Data parzenia</th>
                        <th>Ilość herbaty (g)</th>
                        <th>Ilość wody (ml)</th>
                        <th>Stosunek</th>
                        <th>Opis</th>
                    </tr>
                    {% for brew in brews %}
                    <a>
                        <tr>
                            <td>
                                <a href="{% url "brew-detail" pk=brew.pk %}">
                                    {{ brew.brew_date }}
                                </a>
                            </td>
                            <td>{{ brew.grams|default_if_none:"-" }}</td>
                            <td>{{ brew.water_ml|default_if_none:"-" }}</td>
                            <td>
                                {{ brew.ratio|default_if_none:"-" }}
                                {% if brew.ratio %}
                                    g / 100 ml
                                {% endif %}
                            </td>
                            <td>
                                {% if brew.tasting_notes|length > 25%}
                                    {{ brew.tasting_notes|slice:":25" }}...
                                {% else %}
                                    {{ brew.tasting_notes }}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <h2>Brak parzeń dla tej herbaty!</h2>
            {% endif %}
        </article>
    </main>
{% endblock  %}

tea/templates/tea/create-brew.html
{% extends "base.html" %}
{% load static %}

{% block css_files %}
    <link rel="stylesheet" href="{% static "tea/create-brew.css" %}">
{% endblock %}

{% block title %}Nowe parzenie{% endblock title %}

{% block content %}
    <main id='main-content'>
        <h1>{{ page_title }}</h1>
        <form method="post" id="tea-form">
            {% csrf_token %}
            {% if form.errors %}
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            {% endif %}
            {% for field in form.visible_fields %}
                <div class="field{% if field.errors %} invalid{% endif %}">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <input id="submit_button" type="submit" value="{{ button_text }}">
        </form>
    </main>
{% endblock %}

tea/templates/tea/create-others.html
{% extends "base.html" %}
{% load static %}

{% block css_files %}
    <link rel="stylesheet" href="{% static "tea/create-others.css" %}">
{% endblock %}

{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
    <main id='main-content'>
        <h1>{{ page_title }}</h1>
        <form method="post" id="tea-form">
            {% csrf_token %}
            {% if form.errors %}
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            {% endif %}
            {% for field in form.visible_fields %}
                <div class="field{% if field.errors %} invalid{% endif %}">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <input id="submit_button" type="submit" value="Dodaj">
        </form>
    </main>
{% endblock %}

tea/templates/tea/create-tea.html
{% extends "base.html" %}
{% load static %}

{% block css_files %}
    <link rel="stylesheet" href="{% static "tea/create-tea.css" %}">
{% endblock %}

{% block title %}Nowa herbata{% endblock title %}

{% block content %}
    <main id='main-content'>
        <h1>Nowa herbata</h1>
        <form method="post" id="tea-form">
            {% csrf_token %}
            {% if form.errors %}
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            {% endif %}
            <div id="short-fields">
                <div class='column'>
                    {% for field in form.visible_fields|slice:":6" %}
                        <div class="field{% if field.errors %} invalid{% endif %}">
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                    {% endfor %}
                </div>
                <div class='column'>
                    {% for field in form.visible_fields|slice:"6:-4" %}
                        <div class="field{% if field.errors %} invalid{% endif %}">
                            {{ field.label_tag }}
                            <div class="field-with-plus">
                                {{ field }}
                                <a href="{% url "create-"|add:field.html_name %}" class="plus-href">
                                    <img class="plus-icon" src="{% static "images/plus_icon.svg" %}" alt="Biały plus z zielonym tłem"/>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div id="long-fields">
                {% for field in form.visible_fields|slice:"-4:" %}
                    <div class="field{% if field.errors %} invalid{% endif %}">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
            </div>
            <input id="submit_button" type="submit" value="{{ button_text }}">
        </form>
    </main>
{% endblock %}

tea/templates/tea/main-page.html
{% extends "base.html" %}
{% load static %}

{% block css_files %}
    <link rel="stylesheet" href="{% static "tea/main-page.css" %}">
{% endblock %}

{% block title %}Strona główna{% endblock title %}

{% block content %}
    <main id="main-content">
        <article id="most-recent-teas">
            <h2>Ostatnio dodane herbaty</h2>
            {% if teas.recent %}
                <ul id="recent-teas-list">
                    {% for tea in teas.recent %}
                        <li>
                            <a href="{% url "tea-detail" slug=tea.slug %}">
                                {% if tea.image_set.first.image.url %}
                                    <img class="tea-image" src="{{ tea.image_set.first.image.url }}" alt="Zdjęcie herbaty"/>
                                {% else %}
                                    <img class="tea-image" src="{% static "images/default_tea.png" %}" alt="Rysunek liści herbaty, brak zdjęć"/>
                                {% endif %}
                                <h3>{{ tea.name }}</h3>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>Brak nowych herbat.</p>
                <p>Dodaj herbaty przyciskiem w górnym pasku.</p>
            {% endif %}
        </article>
        <article id="random-teas">
            <h2>Losowe herbaty</h2>
            {% if teas.random %}
                <ul id="random-teas-list">
                    {% for tea in teas.random %}
                    <li>
                        <a href="{% url "tea-detail" slug=tea.slug %}">
                            {% if tea.image_set.first.image.url %}
                            <img class="tea-image" src="{{ tea.image_set.first.image.url }}" alt="Zdjęcie herbaty"/>
                            {% else %}
                            <img class="tea-image" src="{% static "images/default_tea.png" %}" alt="Rysunek liści herbaty, brak zdjęć"/>
                            {% endif %}
                            <h3>{{ tea.name }}</h3>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>Brak herbat do wyświetlenia.</p>
            {% endif %}
            </article>
            <article id="last-viewed-teas">
            <h2>Ostatnio oglądane</h2>
            {% if teas.recent %}
                <ul id="last-viewed-teas-list">
                    {% for tea in teas.last_viewed %}
                        <li>
                            <a href="{% url "tea-detail" slug=tea.slug %}">
                                {% if tea.image_set.first.image.url %}
                                    <img class="tea-image" src="{{ tea.image_set.first.image.url }}" alt="Zdjęcie herbaty"/>
                                {% else %}
                                    <img class="tea-image" src="{% static "images/default_tea.png" %}" alt="Rysunek liści herbaty, brak zdjęć"/>
                                {% endif %}
                                <h3>{{ tea.name }}</h3>
                            </a>
                        </li>
                    {% endfor %}
            {% else %}
                <p>Brak herbat do wyświetlenia.</p>
            {% endif %}
            </ul>
        </article>
    </main>
{% endblock  %}

tea/templates/tea/profile.html
{% extends "base.html" %}
{% load static %}

{% block css_files %}
    <link rel="stylesheet" href="{% static "tea/profile.css" %}">
{% endblock %}

{% block title %}Wybierz profil{% endblock title %}

{% block content %}
    <main id='main-content'>
        <h1>Wybierz profil</h1>
        {% if current_profile == None %}
            <p>Aktualnie nie wybrano żadnego profilu!</p>
            <P>Wybierz profil, aby móc kontynuować lub utwórz nowy.</p>
        {% else %}
            <p>Aktualny profil: {{ current_profile }}</p>
        {% endif %}
        <form method="post" id="profile-select">
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="field">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <input class="big-button" type="submit" value="Wybierz">
        </form>
        <a href="{% url "create-profile" %}" class="new-href">
            <button class="big-button">Dodaj nowy profil</button>
        </a>
    </main>
{% endblock %}

tea/templates/tea/tea-detail.html
{% extends "base.html" %}
{% load static %}

{% block css_files %}
    <link rel="stylesheet" href="{% static "tea/tea-detail.css" %}">
{% endblock %}

{% block title %}{{ tea.name }}{% endblock title %}

{% block content %}
    <main id='details-main'>
        <h1>{{ tea.name }}</h1>
        <div id="above-details">
            <section id="buttons">
                <a href="{% url "tea-update" slug=tea.slug %}" id="update-button" class="button">Edytuj</a>
                <a href="{% url "brews-list" slug=tea.slug %}" id="brews-list-button" class="button">Parzenia</a>
                <a href="{% url "create-brew" slug=tea.slug %}" id="create-brew-button" class="button">Dodaj parzenie</a>
                <a href="" id="delete-button" class="button">Usuń</a>
            </section>
        </div>
        <div id="details">
            <section id="images">
                {% if tea.image_set.first.image.url %}
                <img class="tea-image" src="{{ tea.image_set.first.image.url }}" alt="Zdjęcie herbaty"/>
                {% else %}
                <img class="tea-image" src="{% static "images/default_tea.png" %}" alt="Rysunek liści herbaty, brak zdjęć"/>
                {% endif %}
            </section>
            <div id="text-grid">
                <div class="separator"><b>OGÓLNE INFORMACJE</b></div>
                <section id="tea-information">
                    <p><b>Typ herbaty:</b>
                        {% if tea.type %}
                            {{ tea.type }}
                        {% else %}
                            Brak danych
                        {% endif %}
                    </p>
                    <p><b>Kultywar:</b>
                    {% if tea.cultivar %}
                        {{ tea.cultivar }}
                    {% else %}
                        Brak danych
                    {% endif %}
                    </p>
                    <p><b>Sezon:</b>
                    {% if tea.season %}
                        {{ tea.get_season_display }}
                    {% else %}
                        Brak danych
                    {% endif %}
                    </p>
                    <p><b>Rocznik:</b>
                        {% if tea.year %}
                            {{ tea.year }}
                        {% else %}
                            Brak danych
                        {% endif %}
                    </p>
                    <p><b>Data zbiorów:</b>
                        {% if tea.harvest_date %}
                            {{ tea.harvest_date }}
                        {% else %}
                            Brak danych
                        {% endif %}
                    </p>
                    <p><b>Kraj:</b>
                        {% if tea.country %}
                            {{ tea.country }}
                        {% else %}
                            Brak danych
                        {% endif %}
                    </p>
                    <p><b>Prowincja:</b>
                        {% if tea.province %}
                            {{ tea.province }}
                        {% else %}
                            Brak danych
                        {% endif %}
                    </p>
                    <p><b>Region:</b>
                        {% if tea.region %}
                            {{ tea.region }}
                        {% else %}
                            Brak danych
                        {% endif %}
                    </p>
                </section id="tea-descriptions">
                <div class="separator"><b>OPISY</b></div>
                <section id="description">
                    <h2>Opis sprzedawcy</h2>
                    {% if tea.store_description %}
                        <p>{{ tea.store_description }}</p>
                    {% else %}
                        <p>----</p>
                    {% endif %}
                    <h2>Opis własny</h2>
                    {% if tea.user_description %}
                        <p>{{ tea.user_description }}</p>
                    {% else %}
                        <p>----</p>
                    {% endif %}
                    <h2>Smak i aromat</h2>
                    {% if tea.tasting_notes %}
                        <p>{{ tea.tasting_notes }}</p>
                    {% else %}
                        <p>----</p>
                    {% endif %}
                </section>
                <div class="separator"><b>POZOSTAŁE</b></div>
                <section id="tea-other">
                    <p><b>Pozostało gramów:</b>
                        {% if tea.grams_left %}
                            {{ tea.grams_left }} g
                        {% else %}
                            Brak danych
                        {% endif %}
                    </p>
                    <p><b>Sklep:</b>
                        {% if tea.store %}
                            {{ tea.store }}
                        {% else %}
                            Brak danych
                        {% endif %}
                    </p>
                    <p><b>Cena (100 g):</b>
                        {% if tea.price_per_100_grams %}
                            {{ tea.price_per_100_grams }} zł
                        {% else %}
                            Brak danych
                        {% endif %}
                    </p>
                    <p><b>Dodano:</b>
                        {% if tea.date_added %}
                            {{ tea.date_added.date }}
                        {% else %}
                            Brak danych
                        {% endif %}
                    </p>
                    <p><b>Skończono:</b>
                        {% if tea.date_finished %}
                            {{ tea.date_finished.date }}
                        {% else %}
                            Nadal jest :)
                        {% endif %}
                    </p>
                </section>
                <div class="separator"><b>UWAGI</b></div>
                <section id="additional-notes">
                    {% if tea.additional_notes %}
                        <p>{{ tea.additional_notes }}</p>
                    {% else %}
                        <p>----</p>
                    {% endif %}
                </section>
            </div>
        </div>
    </main>
{% endblock %}